# Generated by Django 3.0.7 on 2020-07-10 19:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(max_length=1000, storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to='')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
