# Generated by Django 3.1 on 2020-08-12 20:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
